### ISSUE TITLE
Option to use persistence without alfresco infrastructure

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/alfresco-identity-service#74]
How would Activiti apps use persistence? Is the idea that the volume needs to make the volume available, that Activiti needs to use alfresco infrastructure or that Activiti should just use h2?

**Comment by ryandawsonuk** [comment]
See https://github.com/Activiti/activiti-cloud-charts/pull/45#issuecomment-464714428

**Comment by svidrascu** [comment]
@ryandawsonuk you can either use postgres as its defined now and get persistence from infra.
Or you can have your own pvc and set it for postgres.
Or you can disable postgres and leave it to the default h2.

**Comment by ryandawsonuk** [comment]
The thing that confuses me is the expectation of `alfresco-volume-claim` that comes from `alfresco-infrastructure-deployment`. If I just deploy vanilla postgres chart to GKE without setting anything it will use defaults to do a volume claim. So for Activiti I'm thinking we can [just put the default back](https://github.com/Activiti/activiti-cloud-charts/pull/51/commits/64d41e183b2dd40abe5eb48ab374988b65657fdf#diff-8e9b5b5cf988767272f16d363998e613R151).

I can see https://github.com/Alfresco/alfresco-infrastructure-deployment/tree/master/helm/alfresco-infrastructure/templates is dealing with different cloud platforms where PVs might need to be different. For activiti to use this it doesn't make much sense to me to add `alfresco-infrastructure-deployment` and disable everything else in the requirements there. Would seem more sensible to me if there were a separate `alfresco-persistent-volume` chart so that we could take just that part.

**Comment by mteodori** [comment]
it is unclear also to me what is the usage of this chart as I did try to install alfresco-identity-service on its own with no values and did break for the same reason

**Comment by svidrascu** [comment]
Its a common volume ( common infra )  so it should reside in the infrastructure chart.
If you choose to have your own volume then please do that.
We are not looking to split this volume into its own chart.

There is no hard dependency between identity and infrastructure trough this volume but we do want to push people to use the identity chart as part of infra.

You can set the existing Claim value to "null" to allow the postgres to create its own dynamic volume.
Or, you can set it to your own claim.

**Comment by mteodori** [comment]
I would set this as default so that it doesn't break and infra can override
this caused a problem to us when installing with content as we need to do some juggling with the persistence option in order to give the opportunity to install the process infra without (for APS2.0) and with (for APS2.1) ACS see https://git.alfresco.com/process-services/alfresco-process-infrastructure-deployment/commit/0307662b8bc7f7bb434123599fd3fbffcee17f83

**Comment by rgauss** [comment]
> For activiti to use this it doesn't make much sense to me to add `alfresco-infrastructure-deployment` and disable everything else in the requirements there.

It is expected that everything else in infrastructure will be needed by Activti/APS once it fully supports publishing Event Gateway events.

The point of using a single volume claim specifically was to make it easier for admins to backup/snapshot everything related to their DBP.

**Comment by mteodori** [comment]
@rgauss that is a different issue, using this chart should be as easy as using the keycloak one

**Comment by ryandawsonuk** [comment]
One suggestion - if the persistence bit were its own chart then you could easily create as many of them as you want and attach them to apps. You could have that chart in the requirements of infrastructure and then you get a default single volume at that level. And we'd also have the option to include it in the requirements of the identity service so that identity service could have its own volume in the way that we want.

Feels like the bigger picture is that having an idea of a pre-existing shared infrastructure jars with the helm tendency to build compositional apps and to have each chart represent a runnable app in its own right.

For many activiti users only particular parts of the DBP will be of interest for their use case. For them it imposes a conceptual overhead if they have to go through every component and work out what things they need disable. Providing an nginx-controller out of the box also strikes me as quite opinionated. 

To me it would be great if we could aim to map out what use-cases look like and make sure the journey is as smooth as possible for the ones that we consider most important.

**Comment by rgauss** [comment]
> that is a different issue, using this chart should be as easy as using the keycloak one

Strictly following Helm best-practices, ideally, yes, and we may end up having an empty `existingClaim` value be the default which is then overridden by infrastructure as a result of this issue.

On the other hand, we **are** trying to encourage the use of the infrastructure chart as the common way to bring in these things.

> if the persistence bit were its own chart then you could easily create as many of them as you want and attach them to apps.

We considered that initially, and as I recall thought it overkill at the time, though that was well before dealing with AWS and Azure persistence and it may be worth revisiting, though again, we want everyone to be using common infrastructure, not picking and choosing individual components within it.

> Feels like the bigger picture is that having an idea of a pre-existing shared infrastructure jars with the helm tendency to build compositional apps and to have each chart represent a runnable app in its own right.

I'm not sure I'm quite grasping what you mean with that wording, but an Activiti App should be relying on existing infrastructure (except in an example/demo scenario) otherwise multiple Activiti Apps would each be deploying their own Identity Service, etc.  Along those same lines, I don't think we'd encourage one uber chart for an organization that included all their Activiti Apps and the DBP (including infrastructure), as they'll almost certainly have different lifecycles.

We also need to account for those that start from ACS and want to add APS/Activiti, and vice versa.

> To me it would be great if we could aim to map out what the use-cases are and make sure the journey is as smooth as possible for the ones that we consider most important.

Absolutely, and we've done that in the past, but we certainly can and should revisit things with today's perspective.

**Comment by ryandawsonuk** [comment]
Yeah perspectives on how we can compose apps have certainly been evolving. One of the factors that has been shaping perspectives in Activiti is Jenkins-X. I think I had this in mind when I made my vague comment about 'compositional apps'.

The Jenkins-X model is that you first install Jenkins-X and with that you get your ingress controller. Thereafter you have a single uber chart that represents a running environment. Individual apps will have their own lifecycles within the uber chart but that gets managed. Each change results in a version increment to a particular chart and that gets updated in the environment requirements file (the uber chart) and when the pipeline does `helm upgrade` then a diff happens automatically and only the changed parts are affected. That diff is actually done by helm and isn't specific to jx (there's also a [tool for seeing the diff in advance](https://github.com/databus23/helm-diff)).

It is ok to add different components progressively in steps with jenkins-x and/or an uber chart and still makes sense to have components that are 'infrastructure'. Basically that translates to steps where extra things are progressively added to a requirements file. We've been working with the Jenkins-X model and got used to this now. I can certainly see the appeal in the alternative of treating different apps as different helm releases. But the single-release uber chart model does seem to play well with CI and my impression is that weaveworks flux works on a similar model where the [overall environment state is being maintained by diffs](https://github.com/weaveworks/flux/blob/master/site/how-it-works.md). 

I also had it in mind that just within the activiti space users are asking if they can easily run just particular components as some users don't want to maintain more running components than they have to. It is tricky to make clear how users can compose charts and turn on and off components but I think a lot of value can be added by thinking of scenarios in advance and either documenting them or trying to cover them with comments on the flags in values files (which might have been enough to resolve my original question that led to this thread).

**Comment by rgauss** [comment]
Yes, I'm familiar with how Jenkins X does things, but the single-release uber chart becomes somewhat more difficult to manage with a larger, complex environment with multiple teams promoting components or entire subsystems to production under different lifecycles that also might depend on non-Kubernetes services.  In some cases the Jenkins-X environment a team uses should simply contain values to point to an existing deployment of a system/platform rather than try to manage it directly as Kubernetes requirements.

> It is tricky to make clear how users can compose charts and turn on and off components

I think the `enabled` flags we use are fairly common practice and should be easy enough for users, and a better option than not having them there or commented out.  Activiti can simple disable the components that aren't yet supported, but again, we expect the Event Gateway events through the adapter to be enabled in the near future which will then require those components.

> a lot of value can be added by thinking of scenarios in advance and either documenting them or trying to cover them with comments on the flags in values files

Most definitely.

We've expanded the scope of this discussion quite a bit here, so probably best to move it to another forum.
